# Generated by Django 4.1.13 on 2023-12-06 03:42

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title_dept', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('office_location', models.URLField()),
                ('office_hours', djongo.models.fields.JSONField()),
                ('research_interests', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'civilResearch',
            },
        ),
    ]
